manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # - name: petejohanson
    #   url-base: https://github.com/petejohanson/
    # - name: badjeff
    #   url-base: https://github.com/badjeff
    # - name: efogdev
    #   url-base: https://github.com/efogdev
    # - name: caksoylar
    #   url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # - name: cirque-input-module
    #   remote: petejohanson
    #   revision: main
    # - name: zmk-rgbled-widget
    #   remote: caksoylar
    #   revision: main
    # - name: zmk-pmw3610-driver
    #   remote: badjeff
    #   revision: main
    # - name: zmk-report-rate-limit
    #   remote: efogdev
    #   revision: main
    # # - name: zmk-input-processor-xyz
    # #   remote: badjeff
    # #   revision: main
    # - name: zmk-rgbled-widget
    #   remote: caksoylar
    #   revision: main
  self:
    path: config
